SELECT
    uu.USER_ID,
    uu.NICKNAME,
    SUM(ub.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD ub
JOIN USED_GOODS_USER uu
ON ub.WRITER_ID = uu.USER_ID
WHERE ub.STATUS = 'DONE'
GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES